version: "3"
services:
    python:
        container_name: felix_python
        build: .
        volumes:
            - './:/opt/src/'
        command: bash -c 'cd /opt/src/python && python3 bot.py'
        restart: always
